services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    network_mode: host
    depends_on: 
      - app
