name: build-test-ship

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-ship:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
