name: build-test-ship

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-ship:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...

      - name: Bundle
        id: bundle
        run: |
          FILENAME="build_$(date +"%Y%m%d_%H%M%S").tar.gz"
          tar -zcvf $FILENAME build
          echo "BUNDLE_NAME=$FILENAME" >> "$GITHUB_OUTPUT"

      - name: Debug
        run: |
          echo "NAME:"
          echo ${{ steps.bundle.outputs.BUNDLE_NAME }}

      - name: Ship
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ${{ steps.bundle.outputs.BUNDLE_NAME }}
          target: ${{ secrets.TARGET_DIR }}
