name: ship

on:
  push:
    branches:
      - main

jobs:
  ship:
    runs-on: ubuntu-20.04
    needs: e2e-test
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make

      - name: Bundle
        id: bundle
        run: |
          FILENAME="build_$(date +"%Y%m%d_%H%M%S").tar.gz"
          tar -zcvf $FILENAME build
          echo "BUNDLE_NAME=$FILENAME" >> "$GITHUB_OUTPUT"

      - name: Ship
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./app/${{ steps.bundle.outputs.BUNDLE_NAME }}
          target: ${{ secrets.TARGET_DIR }}
